### ISSUE TITLE
In interactive clush, local command execution fails (1.7.3 via EPEL6)

### ISSUE THREAD

**Issue by kent-engstrom** [cea-hpc/clustershell#343]
With clustershell-1.7.3-1.el6.noarch from EPEL6:

```
# clush -w n500
Enter 'quit' to leave this interactive mode
Working with nodes: n500
clush> !ls
Exception in thread Task-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.6/site-packages/ClusterShell/Task.py", line 383, in _thread_start
    self.excepthook(*sys.exc_info())
  File "/usr/lib/python2.6/site-packages/ClusterShell/CLI/Clush.py", line 764, in clush_excepthook
    raise exp
AttributeError: 'WorkerPopen' object has no attribute 'key'
```

**Comment by degremont** [comment]
Thanks for reporting.

This was introduced by 22fdbbbe243ef240c690591404121732c6d0ef8d in 1.7.1, which was integrated to fix #289, even if, so far, I do not really understand why...

**Comment by degremont** [comment]
Maybe a more definitive fix would be to make Clush CLI to use ``ev_pickup()``
